# This is a sample workflow to test or replace with your source code.
#
# This workflow passes the region where the workflow is deployed
# to the Wikipedia API and returns a list of related Wikipedia articles.
# A region is retrieved from the GOOGLE_CLOUD_LOCATION system variable
# unless you input your own search term; for example, {"searchTerm": "asia"}.
main:
    steps:
        - parallelStep:
            parallel:
                branches:
                    - opa_assessment:
                        steps:
                            - extract_opa_assessment_data:
                                call: http.post
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/extract_opa_assessment'
                                    auth:
                                        type: OIDC
                            - prepare_opa_assessment_data:
                                call: http.post
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/prepare_opa_assessment'
                                    auth:
                                        type: OIDC
                            - run_sql_source_opa_assessment:
                                call: http.get
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/run_sql_opa_assessment'
                                    query:
                                        sql: 'sql/source_opa_assessment.sql'
                                    auth:
                                        type: OIDC
                            - run_sql_core_opa_assessment:
                                call: http.get
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/run_sql_opa_assessment'
                                    query:
                                        sql: 'sql/core_opa_assessment.sql'
                                    auth:
                                        type: OIDC
                    - opa_properties:
                        steps:
                            - extract_opa_properties_data:
                                call: http.post
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/extract_opa_properties'
                                    auth:
                                        type: OIDC
                            - prepare_opa_properties_data:
                                call: http.post
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/prepare_opa_properties'
                                    auth:
                                        type: OIDC
                            - run_sql_source_opa_properties:
                                call: http.get
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/run_sql_opa_properties'
                                    query:
                                        sql: 'sql/source_opa_properties.sql'
                                    auth:
                                        type: OIDC
                            - run_sql_core_opa_properties:
                                call: http.get
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/run_sql_opa_properties'
                                    query:
                                        sql: 'sql/core_opa_properties.sql'
                                    auth:
                                        type: OIDC
                    - pwd_parcels:
                        steps:
                            - extract_phl_pwd_parcels:
                                call: http.post
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/extract_phl_pwd_parcels'
                                    auth:
                                        type: OIDC
                            - prepare_pwd_parcels:
                                call: http.post
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/prepare_pwd_parcels'
                                    auth:
                                        type: OIDC
                            - run_sql_source_pwd_parcels:
                                call: http.get
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/run_sql_pwd_parcels'
                                    query:
                                        sql: 'sql/source_pwd_parcels.sql'
                                    auth:
                                        type: OIDC
                            - run_sql_core_pwd_parcels:
                                call: http.get
                                args:
                                    url: 'https://us-east4-musa5090s25-team2.cloudfunctions.net/run_sql_pwd_parcels'
                                    query:
                                        sql: 'sql/core_pwd_parcels.sql'
                                    auth:
                                        type: OIDC